### PR TITLE
Adding FarmersOnly Token (FOX) on Harmony

### PR DESCRIPTION
**Pull request by FarmersOnlyFi**

### CODE REVIEW

**Comment by jiro-ono** [comment]
Can you run the logo through here to reduce the size: https://tinypng.com/

Or resize it to 256 x 256

**Comment by FarmersOnlyFi** [comment]
@jiro-ono I ran the image through the link you provided.

**Comment by FarmersOnlyFi** [comment]
@jiro-ono I had our designer make a 256x256 png for this. Thank you.

**Comment by FoxTheFarmer** [comment]
@jiro-ono Is there anything else I need to do here?

Thank you for your time!

**Comment by jiro-ono** [comment]
@FoxTheFarmer Merging this in, but can also add an issue here and I'll add the token to our list for ya: https://github.com/sushiswap/default-token-list/issues

**Pull request merged**
