### PR TITLE
Polygon Telcoin

### PR DESCRIPTION
**Pull request by rileyhoffman**

### CODE REVIEW

**Comment by jiro-ono** [comment]
@rileyhoffman we actually don't need the info.json file, just the logo

If you can remove the info.json and tests pass I'll merge this in

**Comment by rileyhoffman** [comment]
> @rileyhoffman we actually don't need the info.json file, just the logo
> 
> If you can remove the info.json and tests pass I'll merge this in

Will do, thanks!

**Comment by rileyhoffman** [comment]
@jiro-ono Could you help me figure out what's going wrong here? Looks like it might be related to the creation of a new blockchain folder?

**Comment by matthewlilley** [comment]
Thank you @rileyhoffman!

**Pull request merged**
