### PR TITLE
add candle

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by jiro-ono** [comment]
@samisbakedham Is there any liquidity?

**Comment by samisbakedham** [comment]
> @samisbakedham Is there any liquidity?

Yes, Bancor liquidity pool going live.

**Comment by samisbakedham** [comment]
Are we able to merge this, Thank you :)

**Comment by jiro-ono** [comment]
This sushi ser not bancor?

But I'll add it, what's with the pear logo though?

**Comment by samisbakedham** [comment]
> This sushi ser not bancor?
> 
> 
> 
> But I'll add it, what's with the pear logo though?

Yes, Bancor is partnering with CNDL to make a sushiswap liquidity pool for this asset. The Pear logo is for Pear chain, which is a side chain

**Comment by samisbakedham** [comment]
> This sushi ser not bancor?
> 
> 
> 
> But I'll add it, what's with the pear logo though?

Thank you!!

**Comment by jiro-ono** [comment]
> > This sushi ser not bancor?
> > But I'll add it, what's with the pear logo though?
> 
> Yes, Bancor is partnering with CNDL to make a sushiswap liquidity pool for this asset. The Pear logo is for Pear chain, which is a side chain

Ahh gotcha gotcha, that's cool do you by chance have a link to any info on the sushi LP that will be created with bancor? And nice I didn't merge that pear logo in since we don't have support for pear currently.

**Pull request closed without merging**
